// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuG3tNqb4iXEUMbeVI7FmswG-E1QBnQI',
    appId: '1:847615334583:web:126194df6fcdbfea6bd532',
    messagingSenderId: '847615334583',
    projectId: 'fir-flutter-c5396',
    authDomain: 'fir-flutter-c5396.firebaseapp.com',
    storageBucket: 'fir-flutter-c5396.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDavG1yJABAAe8PqbdEa5JQgdQqQzXktW8',
    appId: '1:847615334583:android:f597d387170c0a4f6bd532',
    messagingSenderId: '847615334583',
    projectId: 'fir-flutter-c5396',
    storageBucket: 'fir-flutter-c5396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7oX1z1BJl1d-W9KRr7DLIXb9SBHFYZAY',
    appId: '1:847615334583:ios:09b0939a3b1597906bd532',
    messagingSenderId: '847615334583',
    projectId: 'fir-flutter-c5396',
    storageBucket: 'fir-flutter-c5396.appspot.com',
    iosClientId: '847615334583-cg41rfoki1dsf77s7t58igd09pguinn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7oX1z1BJl1d-W9KRr7DLIXb9SBHFYZAY',
    appId: '1:847615334583:ios:09b0939a3b1597906bd532',
    messagingSenderId: '847615334583',
    projectId: 'fir-flutter-c5396',
    storageBucket: 'fir-flutter-c5396.appspot.com',
    iosClientId: '847615334583-cg41rfoki1dsf77s7t58igd09pguinn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumProjects',
  );
}
